export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const FILTER_QUESTIONS = "FILTER_QUESTIONS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SET_CURRENT = "SET_CURRENT";
